# Site settings
title: Jeremy Ash
header-img: img/OakCropDark.jpg
email: jeremyd.ash@gmail.com
description: "Personal webpage for Jeremy Ash"
baseurl: ""
url: "http://jeremyash.info"
twitter_username: jeremyd_ash
github_username:  jeremyash


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
